import type { Locale } from "@/i18n";

// Textos del Libro de Reclamaciones Virtual. Los campos siguen el art. 5 y el Anexo I del
// Reglamento del Libro de Reclamaciones (D.S. 011-2011-PCM, modificado por D.S. 101-2022-PCM).
const es = {
  metaTitle: "Libro de Reclamaciones virtual",
  metaDescription:
    "Registra tu reclamo o queja en el Libro de Reclamaciones virtual de C&J Software Consulting, conforme al Código de Protección y Defensa del Consumidor.",
  title: "Libro de Reclamaciones",
  lead: "Conforme a lo establecido en el Código de Protección y Defensa del Consumidor (Ley N.° 29571), contamos con un Libro de Reclamaciones virtual a tu disposición.",
  sheet: "Hoja de Reclamación",
  date: "Fecha",
  provider: "Datos del proveedor",
  legalName: "Razón social",
  ruc: "RUC",
  address: "Dirección",
  pending: "Por completar",
  s1: "1. Identificación del consumidor reclamante",
  names: "Nombres y apellidos",
  docType: "Tipo de documento",
  docTypes: ["DNI", "Carné de extranjería", "Pasaporte", "RUC"],
  docNumber: "Número de documento",
  home: "Domicilio",
  phone: "Teléfono",
  email: "Correo electrónico",
  minor: "Soy menor de edad",
  guardian: "Datos del padre, madre o representante",
  guardianName: "Nombres y apellidos",
  s2: "2. Identificación del bien contratado",
  itemType: "Tipo de bien",
  itemTypes: ["Producto", "Servicio"],
  amount: "Monto reclamado (S/)",
  itemDescription: "Descripción del producto o servicio",
  s3: "3. Detalle de la reclamación y pedido del consumidor",
  kind: "Tipo de solicitud",
  kinds: {
    reclamo: { label: "Reclamo", hint: "Disconformidad relacionada a los productos o servicios." },
    queja: {
      label: "Queja",
      hint: "Disconformidad no relacionada a los productos o servicios; o malestar o descontento respecto a la atención al público.",
    },
  },
  detail: "Detalle",
  request: "Pedido",
  s4: "4. Observaciones y acciones adoptadas por el proveedor",
  s4Note: "Esta sección será completada por el proveedor al dar respuesta.",
  consentA: "Declaro que la información es verdadera y acepto la ",
  consentLink: "política de privacidad",
  consentB: ".",
  submit: "Enviar hoja de reclamación",
  sending: "Enviando…",
  legend1:
    "La formulación del reclamo no impide acudir a otras vías de solución de controversias ni es requisito previo para interponer una denuncia ante el INDECOPI.",
  legend2: "El proveedor deberá dar respuesta al reclamo o queja en un plazo no mayor a quince (15) días hábiles improrrogables.",
  required: "Campo obligatorio",
  error: "No pudimos registrar tu hoja. Inténtalo nuevamente o escríbenos a",
  successTitle: "Tu hoja de reclamación fue registrada",
  successBody:
    "Guarda o imprime esta constancia. Te enviamos una copia al correo que indicaste. Te responderemos en un plazo no mayor a quince (15) días hábiles.",
  number: "N.° de hoja",
  registeredAt: "Fecha y hora de registro",
  print: "Imprimir o guardar PDF",
  another: "Registrar otra hoja",
  yes: "Sí",
  no: "No",
};

type ComplaintsDict = typeof es;

const en: ComplaintsDict = {
  metaTitle: "Online Complaints Book",
  metaDescription:
    "File a claim or complaint in the online Complaints Book (Libro de Reclamaciones) of C&J Software Consulting, under Peru's Consumer Protection Code.",
  title: "Complaints Book",
  lead: "As required by Peru's Consumer Protection and Defense Code (Law No. 29571), our online Complaints Book (Libro de Reclamaciones) is available to you.",
  sheet: "Complaint form",
  date: "Date",
  provider: "Provider details",
  legalName: "Company name",
  ruc: "Taxpayer ID (RUC)",
  address: "Address",
  pending: "To be completed",
  s1: "1. Consumer identification",
  names: "Full name",
  docType: "Document type",
  docTypes: ["DNI", "Foreigner ID card", "Passport", "RUC"],
  docNumber: "Document number",
  home: "Address",
  phone: "Phone",
  email: "Email",
  minor: "I am a minor",
  guardian: "Parent or legal representative details",
  guardianName: "Full name",
  s2: "2. Product or service purchased",
  itemType: "Item type",
  itemTypes: ["Product", "Service"],
  amount: "Amount claimed (S/)",
  itemDescription: "Description of the product or service",
  s3: "3. Details of the claim and consumer request",
  kind: "Request type",
  kinds: {
    reclamo: { label: "Claim (reclamo)", hint: "Disagreement related to the products or services." },
    queja: {
      label: "Complaint (queja)",
      hint: "Disagreement not related to the products or services; or dissatisfaction with customer service.",
    },
  },
  detail: "Details",
  request: "Request",
  s4: "4. Provider's observations and actions taken",
  s4Note: "This section will be completed by the provider when responding.",
  consentA: "I declare the information is true and accept the ",
  consentLink: "privacy policy",
  consentB: ".",
  submit: "Submit complaint form",
  sending: "Sending…",
  legend1:
    "Filing a claim does not prevent you from using other dispute resolution channels, nor is it a prerequisite for filing a complaint with INDECOPI.",
  legend2: "The provider must answer the claim or complaint within no more than fifteen (15) non-extendable business days.",
  required: "Required field",
  error: "We couldn't register your form. Please try again or email us at",
  successTitle: "Your complaint form has been registered",
  successBody:
    "Save or print this receipt. We sent a copy to the email you provided. We will reply within no more than fifteen (15) business days.",
  number: "Form No.",
  registeredAt: "Date and time of registration",
  print: "Print or save as PDF",
  another: "Register another form",
  yes: "Yes",
  no: "No",
};

export const complaints: Record<Locale, ComplaintsDict> = { es, en };
export type { ComplaintsDict };
